### ISSUE TITLE
sed issue on macOS

### ISSUE THREAD

**Issue by alex-taffe** [jersacct/2016PilotOneClick#2]
For whatever reason the sed installed with macOS does not work with the -r option. The solution is to run `brew install gnu-sed` and then change any instances of sed in the script to `gsed`.

I'm not sure if this should maybe be specified in the read me or if we could somehow conditionally check this in the bash script

**Comment by codeage** [comment]
You should change -r to -E on macOS.

```
uname=`uname`
echo "OS type: $uname"

echo "Getting signature of $1..."
if [ "$uname" = "Darwin" ]; then
	sig=`java -jar bin/GetAndroidSig.jar "$1" | grep "To char" | sed -E 's/^.{9}//'`
else
	sig=`java -jar bin/GetAndroidSig.jar "$1" | grep "To char" | sed -r 's/^.{9}//'`
fi
echo "Signature: $sig"
```
